# Generated by Django 4.2.11 on 2024-07-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
